// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceAgent_ListDevices_FullMethodName            = "/agent.DeviceAgent/ListDevices"
	DeviceAgent_ConnectDevice_FullMethodName          = "/agent.DeviceAgent/ConnectDevice"
	DeviceAgent_DisconnectDevice_FullMethodName       = "/agent.DeviceAgent/DisconnectDevice"
	DeviceAgent_RunBenchmark_FullMethodName           = "/agent.DeviceAgent/RunBenchmark"
	DeviceAgent_GetJobStatus_FullMethodName           = "/agent.DeviceAgent/GetJobStatus"
	DeviceAgent_SubscribeJobProgress_FullMethodName   = "/agent.DeviceAgent/SubscribeJobProgress"
	DeviceAgent_GetBenchmarkResult_FullMethodName     = "/agent.DeviceAgent/GetBenchmarkResult"
	DeviceAgent_DeleteJob_FullMethodName              = "/agent.DeviceAgent/DeleteJob"
	DeviceAgent_CancelJob_FullMethodName              = "/agent.DeviceAgent/CancelJob"
	DeviceAgent_RunScenario_FullMethodName            = "/agent.DeviceAgent/RunScenario"
	DeviceAgent_StartTrace_FullMethodName             = "/agent.DeviceAgent/StartTrace"
	DeviceAgent_StopTrace_FullMethodName              = "/agent.DeviceAgent/StopTrace"
	DeviceAgent_GetTraceResult_FullMethodName         = "/agent.DeviceAgent/GetTraceResult"
	DeviceAgent_GetTraceRawData_FullMethodName        = "/agent.DeviceAgent/GetTraceRawData"
	DeviceAgent_UploadTraceToMinio_FullMethodName     = "/agent.DeviceAgent/UploadTraceToMinio"
	DeviceAgent_UploadBenchmarkToMinio_FullMethodName = "/agent.DeviceAgent/UploadBenchmarkToMinio"
	DeviceAgent_UploadTraceArchive_FullMethodName     = "/agent.DeviceAgent/UploadTraceArchive"
	DeviceAgent_GetArchiveFilesInfo_FullMethodName    = "/agent.DeviceAgent/GetArchiveFilesInfo"
	DeviceAgent_MonitorDevices_FullMethodName         = "/agent.DeviceAgent/MonitorDevices"
	DeviceAgent_ListInstalledApps_FullMethodName      = "/agent.DeviceAgent/ListInstalledApps"
	DeviceAgent_StartRecording_FullMethodName         = "/agent.DeviceAgent/StartRecording"
	DeviceAgent_StopRecording_FullMethodName          = "/agent.DeviceAgent/StopRecording"
	DeviceAgent_ReplayMacro_FullMethodName            = "/agent.DeviceAgent/ReplayMacro"
	DeviceAgent_TakeScreenshot_FullMethodName         = "/agent.DeviceAgent/TakeScreenshot"
	DeviceAgent_ScreenshotOcr_FullMethodName          = "/agent.DeviceAgent/ScreenshotOcr"
	DeviceAgent_ReparseTrace_FullMethodName           = "/agent.DeviceAgent/ReparseTrace"
	DeviceAgent_Shell_FullMethodName                  = "/agent.DeviceAgent/Shell"
)

// DeviceAgentClient is the client API for DeviceAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceAgentClient interface {
	// Device Management
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	ConnectDevice(ctx context.Context, in *ConnectDeviceRequest, opts ...grpc.CallOption) (*ConnectDeviceResponse, error)
	DisconnectDevice(ctx context.Context, in *DisconnectDeviceRequest, opts ...grpc.CallOption) (*DisconnectDeviceResponse, error)
	// Benchmarking
	RunBenchmark(ctx context.Context, in *RunBenchmarkRequest, opts ...grpc.CallOption) (*RunBenchmarkResponse, error)
	GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error)
	SubscribeJobProgress(ctx context.Context, in *SubscribeJobProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error)
	GetBenchmarkResult(ctx context.Context, in *GetBenchmarkResultRequest, opts ...grpc.CallOption) (*GetBenchmarkResultResponse, error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error)
	CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error)
	// Scenario
	RunScenario(ctx context.Context, in *RunScenarioRequest, opts ...grpc.CallOption) (*RunScenarioResponse, error)
	// Trace
	StartTrace(ctx context.Context, in *StartTraceRequest, opts ...grpc.CallOption) (*StartTraceResponse, error)
	StopTrace(ctx context.Context, in *StopTraceRequest, opts ...grpc.CallOption) (*StopTraceResponse, error)
	GetTraceResult(ctx context.Context, in *GetTraceResultRequest, opts ...grpc.CallOption) (*GetTraceResultResponse, error)
	GetTraceRawData(ctx context.Context, in *GetTraceRawDataRequest, opts ...grpc.CallOption) (*GetTraceRawDataResponse, error)
	// Upload
	UploadTraceToMinio(ctx context.Context, in *UploadTraceRequest, opts ...grpc.CallOption) (*UploadTraceResponse, error)
	UploadBenchmarkToMinio(ctx context.Context, in *UploadBenchmarkRequest, opts ...grpc.CallOption) (*UploadBenchmarkResponse, error)
	// Trace Archive — presigned URL 받아 nginx 경유 PUT (raw + realtime parquet)
	UploadTraceArchive(ctx context.Context, in *UploadTraceArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UploadTraceArchiveProgress], error)
	// Archive 대상 파일 메타 조회 — portal 이 init 시 정확한 file size/count 를 알고 presign 발급
	GetArchiveFilesInfo(ctx context.Context, in *GetArchiveFilesInfoRequest, opts ...grpc.CallOption) (*GetArchiveFilesInfoResponse, error)
	// Monitoring
	MonitorDevices(ctx context.Context, in *MonitorDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceMetrics], error)
	// App Macro (이벤트 녹화/재생 + OCR)
	ListInstalledApps(ctx context.Context, in *ListInstalledAppsRequest, opts ...grpc.CallOption) (*ListInstalledAppsResponse, error)
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error)
	StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error)
	ReplayMacro(ctx context.Context, in *ReplayMacroRequest, opts ...grpc.CallOption) (*ReplayMacroResponse, error)
	TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error)
	ScreenshotOcr(ctx context.Context, in *ScreenshotOcrRequest, opts ...grpc.CallOption) (*ScreenshotOcrResponse, error)
	// Trace Reparse
	ReparseTrace(ctx context.Context, in *ReparseTraceRequest, opts ...grpc.CallOption) (*ReparseTraceResponse, error)
	// Interactive shell (PTY) — bidi-streaming.
	// 첫 메시지는 반드시 ShellClientMsg.start (device_id, cols, rows) 이어야 한다.
	// 이후 input / resize 메시지로 양방향 통신. 종료 시 server 가 ShellServerMsg.exit 전송.
	Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellClientMsg, ShellServerMsg], error)
}

type deviceAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceAgentClient(cc grpc.ClientConnInterface) DeviceAgentClient {
	return &deviceAgentClient{cc}
}

func (c *deviceAgentClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) ConnectDevice(ctx context.Context, in *ConnectDeviceRequest, opts ...grpc.CallOption) (*ConnectDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ConnectDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) DisconnectDevice(ctx context.Context, in *DisconnectDeviceRequest, opts ...grpc.CallOption) (*DisconnectDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_DisconnectDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) RunBenchmark(ctx context.Context, in *RunBenchmarkRequest, opts ...grpc.CallOption) (*RunBenchmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunBenchmarkResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_RunBenchmark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) GetJobStatus(ctx context.Context, in *GetJobStatusRequest, opts ...grpc.CallOption) (*GetJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobStatusResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_GetJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) SubscribeJobProgress(ctx context.Context, in *SubscribeJobProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceAgent_ServiceDesc.Streams[0], DeviceAgent_SubscribeJobProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeJobProgressRequest, JobProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_SubscribeJobProgressClient = grpc.ServerStreamingClient[JobProgress]

func (c *deviceAgentClient) GetBenchmarkResult(ctx context.Context, in *GetBenchmarkResultRequest, opts ...grpc.CallOption) (*GetBenchmarkResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBenchmarkResultResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_GetBenchmarkResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteJobResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) CancelJob(ctx context.Context, in *CancelJobRequest, opts ...grpc.CallOption) (*CancelJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelJobResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_CancelJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) RunScenario(ctx context.Context, in *RunScenarioRequest, opts ...grpc.CallOption) (*RunScenarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunScenarioResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_RunScenario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) StartTrace(ctx context.Context, in *StartTraceRequest, opts ...grpc.CallOption) (*StartTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartTraceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_StartTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) StopTrace(ctx context.Context, in *StopTraceRequest, opts ...grpc.CallOption) (*StopTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopTraceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_StopTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) GetTraceResult(ctx context.Context, in *GetTraceResultRequest, opts ...grpc.CallOption) (*GetTraceResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceResultResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_GetTraceResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) GetTraceRawData(ctx context.Context, in *GetTraceRawDataRequest, opts ...grpc.CallOption) (*GetTraceRawDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTraceRawDataResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_GetTraceRawData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) UploadTraceToMinio(ctx context.Context, in *UploadTraceRequest, opts ...grpc.CallOption) (*UploadTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTraceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_UploadTraceToMinio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) UploadBenchmarkToMinio(ctx context.Context, in *UploadBenchmarkRequest, opts ...grpc.CallOption) (*UploadBenchmarkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadBenchmarkResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_UploadBenchmarkToMinio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) UploadTraceArchive(ctx context.Context, in *UploadTraceArchiveRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UploadTraceArchiveProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceAgent_ServiceDesc.Streams[1], DeviceAgent_UploadTraceArchive_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadTraceArchiveRequest, UploadTraceArchiveProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_UploadTraceArchiveClient = grpc.ServerStreamingClient[UploadTraceArchiveProgress]

func (c *deviceAgentClient) GetArchiveFilesInfo(ctx context.Context, in *GetArchiveFilesInfoRequest, opts ...grpc.CallOption) (*GetArchiveFilesInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetArchiveFilesInfoResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_GetArchiveFilesInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) MonitorDevices(ctx context.Context, in *MonitorDevicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceMetrics], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceAgent_ServiceDesc.Streams[2], DeviceAgent_MonitorDevices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MonitorDevicesRequest, DeviceMetrics]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_MonitorDevicesClient = grpc.ServerStreamingClient[DeviceMetrics]

func (c *deviceAgentClient) ListInstalledApps(ctx context.Context, in *ListInstalledAppsRequest, opts ...grpc.CallOption) (*ListInstalledAppsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstalledAppsResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ListInstalledApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*StartRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartRecordingResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*StopRecordingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRecordingResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) ReplayMacro(ctx context.Context, in *ReplayMacroRequest, opts ...grpc.CallOption) (*ReplayMacroResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReplayMacroResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ReplayMacro_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) TakeScreenshot(ctx context.Context, in *TakeScreenshotRequest, opts ...grpc.CallOption) (*TakeScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeScreenshotResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_TakeScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) ScreenshotOcr(ctx context.Context, in *ScreenshotOcrRequest, opts ...grpc.CallOption) (*ScreenshotOcrResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotOcrResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ScreenshotOcr_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) ReparseTrace(ctx context.Context, in *ReparseTraceRequest, opts ...grpc.CallOption) (*ReparseTraceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReparseTraceResponse)
	err := c.cc.Invoke(ctx, DeviceAgent_ReparseTrace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceAgentClient) Shell(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ShellClientMsg, ShellServerMsg], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeviceAgent_ServiceDesc.Streams[3], DeviceAgent_Shell_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ShellClientMsg, ShellServerMsg]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_ShellClient = grpc.BidiStreamingClient[ShellClientMsg, ShellServerMsg]

// DeviceAgentServer is the server API for DeviceAgent service.
// All implementations must embed UnimplementedDeviceAgentServer
// for forward compatibility.
type DeviceAgentServer interface {
	// Device Management
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	ConnectDevice(context.Context, *ConnectDeviceRequest) (*ConnectDeviceResponse, error)
	DisconnectDevice(context.Context, *DisconnectDeviceRequest) (*DisconnectDeviceResponse, error)
	// Benchmarking
	RunBenchmark(context.Context, *RunBenchmarkRequest) (*RunBenchmarkResponse, error)
	GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error)
	SubscribeJobProgress(*SubscribeJobProgressRequest, grpc.ServerStreamingServer[JobProgress]) error
	GetBenchmarkResult(context.Context, *GetBenchmarkResultRequest) (*GetBenchmarkResultResponse, error)
	DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error)
	CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error)
	// Scenario
	RunScenario(context.Context, *RunScenarioRequest) (*RunScenarioResponse, error)
	// Trace
	StartTrace(context.Context, *StartTraceRequest) (*StartTraceResponse, error)
	StopTrace(context.Context, *StopTraceRequest) (*StopTraceResponse, error)
	GetTraceResult(context.Context, *GetTraceResultRequest) (*GetTraceResultResponse, error)
	GetTraceRawData(context.Context, *GetTraceRawDataRequest) (*GetTraceRawDataResponse, error)
	// Upload
	UploadTraceToMinio(context.Context, *UploadTraceRequest) (*UploadTraceResponse, error)
	UploadBenchmarkToMinio(context.Context, *UploadBenchmarkRequest) (*UploadBenchmarkResponse, error)
	// Trace Archive — presigned URL 받아 nginx 경유 PUT (raw + realtime parquet)
	UploadTraceArchive(*UploadTraceArchiveRequest, grpc.ServerStreamingServer[UploadTraceArchiveProgress]) error
	// Archive 대상 파일 메타 조회 — portal 이 init 시 정확한 file size/count 를 알고 presign 발급
	GetArchiveFilesInfo(context.Context, *GetArchiveFilesInfoRequest) (*GetArchiveFilesInfoResponse, error)
	// Monitoring
	MonitorDevices(*MonitorDevicesRequest, grpc.ServerStreamingServer[DeviceMetrics]) error
	// App Macro (이벤트 녹화/재생 + OCR)
	ListInstalledApps(context.Context, *ListInstalledAppsRequest) (*ListInstalledAppsResponse, error)
	StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error)
	StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error)
	ReplayMacro(context.Context, *ReplayMacroRequest) (*ReplayMacroResponse, error)
	TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error)
	ScreenshotOcr(context.Context, *ScreenshotOcrRequest) (*ScreenshotOcrResponse, error)
	// Trace Reparse
	ReparseTrace(context.Context, *ReparseTraceRequest) (*ReparseTraceResponse, error)
	// Interactive shell (PTY) — bidi-streaming.
	// 첫 메시지는 반드시 ShellClientMsg.start (device_id, cols, rows) 이어야 한다.
	// 이후 input / resize 메시지로 양방향 통신. 종료 시 server 가 ShellServerMsg.exit 전송.
	Shell(grpc.BidiStreamingServer[ShellClientMsg, ShellServerMsg]) error
	mustEmbedUnimplementedDeviceAgentServer()
}

// UnimplementedDeviceAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceAgentServer struct{}

func (UnimplementedDeviceAgentServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedDeviceAgentServer) ConnectDevice(context.Context, *ConnectDeviceRequest) (*ConnectDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectDevice not implemented")
}
func (UnimplementedDeviceAgentServer) DisconnectDevice(context.Context, *DisconnectDeviceRequest) (*DisconnectDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectDevice not implemented")
}
func (UnimplementedDeviceAgentServer) RunBenchmark(context.Context, *RunBenchmarkRequest) (*RunBenchmarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunBenchmark not implemented")
}
func (UnimplementedDeviceAgentServer) GetJobStatus(context.Context, *GetJobStatusRequest) (*GetJobStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobStatus not implemented")
}
func (UnimplementedDeviceAgentServer) SubscribeJobProgress(*SubscribeJobProgressRequest, grpc.ServerStreamingServer[JobProgress]) error {
	return status.Error(codes.Unimplemented, "method SubscribeJobProgress not implemented")
}
func (UnimplementedDeviceAgentServer) GetBenchmarkResult(context.Context, *GetBenchmarkResultRequest) (*GetBenchmarkResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBenchmarkResult not implemented")
}
func (UnimplementedDeviceAgentServer) DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedDeviceAgentServer) CancelJob(context.Context, *CancelJobRequest) (*CancelJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelJob not implemented")
}
func (UnimplementedDeviceAgentServer) RunScenario(context.Context, *RunScenarioRequest) (*RunScenarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunScenario not implemented")
}
func (UnimplementedDeviceAgentServer) StartTrace(context.Context, *StartTraceRequest) (*StartTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrace not implemented")
}
func (UnimplementedDeviceAgentServer) StopTrace(context.Context, *StopTraceRequest) (*StopTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopTrace not implemented")
}
func (UnimplementedDeviceAgentServer) GetTraceResult(context.Context, *GetTraceResultRequest) (*GetTraceResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceResult not implemented")
}
func (UnimplementedDeviceAgentServer) GetTraceRawData(context.Context, *GetTraceRawDataRequest) (*GetTraceRawDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTraceRawData not implemented")
}
func (UnimplementedDeviceAgentServer) UploadTraceToMinio(context.Context, *UploadTraceRequest) (*UploadTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadTraceToMinio not implemented")
}
func (UnimplementedDeviceAgentServer) UploadBenchmarkToMinio(context.Context, *UploadBenchmarkRequest) (*UploadBenchmarkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadBenchmarkToMinio not implemented")
}
func (UnimplementedDeviceAgentServer) UploadTraceArchive(*UploadTraceArchiveRequest, grpc.ServerStreamingServer[UploadTraceArchiveProgress]) error {
	return status.Error(codes.Unimplemented, "method UploadTraceArchive not implemented")
}
func (UnimplementedDeviceAgentServer) GetArchiveFilesInfo(context.Context, *GetArchiveFilesInfoRequest) (*GetArchiveFilesInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetArchiveFilesInfo not implemented")
}
func (UnimplementedDeviceAgentServer) MonitorDevices(*MonitorDevicesRequest, grpc.ServerStreamingServer[DeviceMetrics]) error {
	return status.Error(codes.Unimplemented, "method MonitorDevices not implemented")
}
func (UnimplementedDeviceAgentServer) ListInstalledApps(context.Context, *ListInstalledAppsRequest) (*ListInstalledAppsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstalledApps not implemented")
}
func (UnimplementedDeviceAgentServer) StartRecording(context.Context, *StartRecordingRequest) (*StartRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedDeviceAgentServer) StopRecording(context.Context, *StopRecordingRequest) (*StopRecordingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedDeviceAgentServer) ReplayMacro(context.Context, *ReplayMacroRequest) (*ReplayMacroResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplayMacro not implemented")
}
func (UnimplementedDeviceAgentServer) TakeScreenshot(context.Context, *TakeScreenshotRequest) (*TakeScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TakeScreenshot not implemented")
}
func (UnimplementedDeviceAgentServer) ScreenshotOcr(context.Context, *ScreenshotOcrRequest) (*ScreenshotOcrResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ScreenshotOcr not implemented")
}
func (UnimplementedDeviceAgentServer) ReparseTrace(context.Context, *ReparseTraceRequest) (*ReparseTraceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReparseTrace not implemented")
}
func (UnimplementedDeviceAgentServer) Shell(grpc.BidiStreamingServer[ShellClientMsg, ShellServerMsg]) error {
	return status.Error(codes.Unimplemented, "method Shell not implemented")
}
func (UnimplementedDeviceAgentServer) mustEmbedUnimplementedDeviceAgentServer() {}
func (UnimplementedDeviceAgentServer) testEmbeddedByValue()                     {}

// UnsafeDeviceAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceAgentServer will
// result in compilation errors.
type UnsafeDeviceAgentServer interface {
	mustEmbedUnimplementedDeviceAgentServer()
}

func RegisterDeviceAgentServer(s grpc.ServiceRegistrar, srv DeviceAgentServer) {
	// If the following call panics, it indicates UnimplementedDeviceAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceAgent_ServiceDesc, srv)
}

func _DeviceAgent_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_ConnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ConnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ConnectDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ConnectDevice(ctx, req.(*ConnectDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_DisconnectDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).DisconnectDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_DisconnectDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).DisconnectDevice(ctx, req.(*DisconnectDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_RunBenchmark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunBenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).RunBenchmark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_RunBenchmark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).RunBenchmark(ctx, req.(*RunBenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_GetJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).GetJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_GetJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).GetJobStatus(ctx, req.(*GetJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_SubscribeJobProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeJobProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceAgentServer).SubscribeJobProgress(m, &grpc.GenericServerStream[SubscribeJobProgressRequest, JobProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_SubscribeJobProgressServer = grpc.ServerStreamingServer[JobProgress]

func _DeviceAgent_GetBenchmarkResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBenchmarkResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).GetBenchmarkResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_GetBenchmarkResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).GetBenchmarkResult(ctx, req.(*GetBenchmarkResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).DeleteJob(ctx, req.(*DeleteJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_CancelJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).CancelJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_CancelJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).CancelJob(ctx, req.(*CancelJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_RunScenario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunScenarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).RunScenario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_RunScenario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).RunScenario(ctx, req.(*RunScenarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_StartTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).StartTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_StartTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).StartTrace(ctx, req.(*StartTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_StopTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).StopTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_StopTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).StopTrace(ctx, req.(*StopTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_GetTraceResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).GetTraceResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_GetTraceResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).GetTraceResult(ctx, req.(*GetTraceResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_GetTraceRawData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTraceRawDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).GetTraceRawData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_GetTraceRawData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).GetTraceRawData(ctx, req.(*GetTraceRawDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_UploadTraceToMinio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).UploadTraceToMinio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_UploadTraceToMinio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).UploadTraceToMinio(ctx, req.(*UploadTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_UploadBenchmarkToMinio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadBenchmarkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).UploadBenchmarkToMinio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_UploadBenchmarkToMinio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).UploadBenchmarkToMinio(ctx, req.(*UploadBenchmarkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_UploadTraceArchive_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UploadTraceArchiveRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceAgentServer).UploadTraceArchive(m, &grpc.GenericServerStream[UploadTraceArchiveRequest, UploadTraceArchiveProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_UploadTraceArchiveServer = grpc.ServerStreamingServer[UploadTraceArchiveProgress]

func _DeviceAgent_GetArchiveFilesInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArchiveFilesInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).GetArchiveFilesInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_GetArchiveFilesInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).GetArchiveFilesInfo(ctx, req.(*GetArchiveFilesInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_MonitorDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MonitorDevicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DeviceAgentServer).MonitorDevices(m, &grpc.GenericServerStream[MonitorDevicesRequest, DeviceMetrics]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_MonitorDevicesServer = grpc.ServerStreamingServer[DeviceMetrics]

func _DeviceAgent_ListInstalledApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstalledAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ListInstalledApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ListInstalledApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ListInstalledApps(ctx, req.(*ListInstalledAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).StopRecording(ctx, req.(*StopRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_ReplayMacro_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplayMacroRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ReplayMacro(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ReplayMacro_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ReplayMacro(ctx, req.(*ReplayMacroRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_TakeScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).TakeScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_TakeScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).TakeScreenshot(ctx, req.(*TakeScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_ScreenshotOcr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotOcrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ScreenshotOcr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ScreenshotOcr_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ScreenshotOcr(ctx, req.(*ScreenshotOcrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_ReparseTrace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReparseTraceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceAgentServer).ReparseTrace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceAgent_ReparseTrace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceAgentServer).ReparseTrace(ctx, req.(*ReparseTraceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceAgent_Shell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeviceAgentServer).Shell(&grpc.GenericServerStream[ShellClientMsg, ShellServerMsg]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeviceAgent_ShellServer = grpc.BidiStreamingServer[ShellClientMsg, ShellServerMsg]

// DeviceAgent_ServiceDesc is the grpc.ServiceDesc for DeviceAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.DeviceAgent",
	HandlerType: (*DeviceAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListDevices",
			Handler:    _DeviceAgent_ListDevices_Handler,
		},
		{
			MethodName: "ConnectDevice",
			Handler:    _DeviceAgent_ConnectDevice_Handler,
		},
		{
			MethodName: "DisconnectDevice",
			Handler:    _DeviceAgent_DisconnectDevice_Handler,
		},
		{
			MethodName: "RunBenchmark",
			Handler:    _DeviceAgent_RunBenchmark_Handler,
		},
		{
			MethodName: "GetJobStatus",
			Handler:    _DeviceAgent_GetJobStatus_Handler,
		},
		{
			MethodName: "GetBenchmarkResult",
			Handler:    _DeviceAgent_GetBenchmarkResult_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _DeviceAgent_DeleteJob_Handler,
		},
		{
			MethodName: "CancelJob",
			Handler:    _DeviceAgent_CancelJob_Handler,
		},
		{
			MethodName: "RunScenario",
			Handler:    _DeviceAgent_RunScenario_Handler,
		},
		{
			MethodName: "StartTrace",
			Handler:    _DeviceAgent_StartTrace_Handler,
		},
		{
			MethodName: "StopTrace",
			Handler:    _DeviceAgent_StopTrace_Handler,
		},
		{
			MethodName: "GetTraceResult",
			Handler:    _DeviceAgent_GetTraceResult_Handler,
		},
		{
			MethodName: "GetTraceRawData",
			Handler:    _DeviceAgent_GetTraceRawData_Handler,
		},
		{
			MethodName: "UploadTraceToMinio",
			Handler:    _DeviceAgent_UploadTraceToMinio_Handler,
		},
		{
			MethodName: "UploadBenchmarkToMinio",
			Handler:    _DeviceAgent_UploadBenchmarkToMinio_Handler,
		},
		{
			MethodName: "GetArchiveFilesInfo",
			Handler:    _DeviceAgent_GetArchiveFilesInfo_Handler,
		},
		{
			MethodName: "ListInstalledApps",
			Handler:    _DeviceAgent_ListInstalledApps_Handler,
		},
		{
			MethodName: "StartRecording",
			Handler:    _DeviceAgent_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _DeviceAgent_StopRecording_Handler,
		},
		{
			MethodName: "ReplayMacro",
			Handler:    _DeviceAgent_ReplayMacro_Handler,
		},
		{
			MethodName: "TakeScreenshot",
			Handler:    _DeviceAgent_TakeScreenshot_Handler,
		},
		{
			MethodName: "ScreenshotOcr",
			Handler:    _DeviceAgent_ScreenshotOcr_Handler,
		},
		{
			MethodName: "ReparseTrace",
			Handler:    _DeviceAgent_ReparseTrace_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeJobProgress",
			Handler:       _DeviceAgent_SubscribeJobProgress_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadTraceArchive",
			Handler:       _DeviceAgent_UploadTraceArchive_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MonitorDevices",
			Handler:       _DeviceAgent_MonitorDevices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Shell",
			Handler:       _DeviceAgent_Shell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
